name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B build && cmake --build build
  
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B build && cmake --build build
